import { Geist, Geist_Mono, Pacifico, Corinthia,La_Belle_Aurore  } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const pacifico = Pacifico({
  variable: "--font-pacifico",
  subsets: ["latin"],
  weight: ['400']
});
const corinthia = Corinthia({
  variable: "--font-corinthia",
  subsets: ["latin"],
  weight: ['400', '700']
});
const laBelleAurore = Corinthia({
  variable: "--font-la-belle-aurore",
  subsets: ["latin"],
  weight: ['400', '700']
});

export const metadata = {
  title: "Make Me Horny - Most horny porn links and content",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${laBelleAurore.variable} ${corinthia.variable} ${pacifico.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
